dcache: fix implicit wait.h include in <linux/dcache.h>
To fix:

  In file included from fs/notify/fsnotify.c:19:0:
  ./include/linux/dcache.h:103:3: error: unknown type name ‘wait_queue_head_t’
     wait_queue_head_t *d_wait; /* in-lookup ones only */
     ^
  ./include/linux/dcache.h:233:6: error: unknown type name ‘wait_queue_head_t’
        wait_queue_head_t *);
        ^
  make[2]: *** [fs/notify/fsnotify.o] Error 1

The same fail appears in file included from security/security.c:15:0:

This was observed in -rt, but it is quite possible the same issue will
appear for certain configs or arch builds on mainline as well.

Fixes: d9171b934526 ("parallel lookups machinery, part 4 (and last)")
Cc: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>