rbtree_augmented: fix implicit rcu assign pointer dependency
To fix:

In file included from include/linux/interval_tree_generic.h:22:0,
                 from lib/interval_tree.c:2:
include/linux/rbtree_augmented.h: In function ‘__rb_change_child_rcu’:
include/linux/rbtree_augmented.h:139:4: error: implicit declaration of function ‘rcu_assign_pointer’ [-Werror=implicit-function-declaration]
    rcu_assign_pointer(parent->rb_left, new);

...which shows up on some -rt builds once the rb_replace_node_rcu was
added.  Since rcu_assign_pointer is clearly used, just add the header
for it to the file in question.

Fixes: c1adf20052d80 ("Introduce rb_replace_node_rcu()")
Cc: David Howells <dhowells@redhat.com>
Cc: Peter Zijlstra (Intel) <peterz@infradead.org>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>